version: '3.8'

services:
  experiment-1:
    image: experiment
    volumes:
      - .:/app
    command: python Code/tm_1.py
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
    build:
      context: .
      dockerfile: ./Dockerfile
  experiment-2:
    image: experiment
    volumes:
      - .:/app
    command: python Code/tm_2.py
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
  experiment-3:
    image: experiment
    volumes:
      - .:/app
    command: python Code/tm_3.py
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["3"]
              capabilities: [gpu]
  experiment-4:
    image: experiment
    volumes:
      - .:/app
    command: python Code/tm_4.py
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["4"]
              capabilities: [gpu]
  experiment-5:
    image: experiment
    volumes:
      - .:/app
    command: python Code/tm_5.py
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["5"]
              capabilities: [gpu]
  experiment-6:
    image: experiment
    volumes:
      - .:/app
    command: python Code/tm_6.py
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["6"]
              capabilities: [gpu]
