version: '3.4'

services:
  experiment-1:
    image: experiment
    command: python Code/experiment-5.py
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
  experiment-2:
    image: experiment
    command: python Code/experiment-6.py
    restart: on-failure
